/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTurmasRouteImport } from './routes/_app/turmas'
import { Route as AppProfessoresRouteImport } from './routes/_app/professores'
import { Route as AppMensalidadesRouteImport } from './routes/_app/mensalidades'
import { Route as AppAlunosRouteImport } from './routes/_app/alunos'
import { Route as AppMasterIndexRouteImport } from './routes/_app/master/index'
import { Route as AppAlunosIdRouteImport } from './routes/_app/alunos.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTurmasRoute = AppTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessoresRoute = AppProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => AppRoute,
} as any)
const AppMensalidadesRoute = AppMensalidadesRouteImport.update({
  id: '/mensalidades',
  path: '/mensalidades',
  getParentRoute: () => AppRoute,
} as any)
const AppAlunosRoute = AppAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterIndexRoute = AppMasterIndexRouteImport.update({
  id: '/master/',
  path: '/master/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlunosIdRoute = AppAlunosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAlunosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/alunos': typeof AppAlunosRouteWithChildren
  '/mensalidades': typeof AppMensalidadesRoute
  '/professores': typeof AppProfessoresRoute
  '/turmas': typeof AppTurmasRoute
  '/alunos/$id': typeof AppAlunosIdRoute
  '/master/': typeof AppMasterIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/alunos': typeof AppAlunosRouteWithChildren
  '/mensalidades': typeof AppMensalidadesRoute
  '/professores': typeof AppProfessoresRoute
  '/turmas': typeof AppTurmasRoute
  '/': typeof AppIndexRoute
  '/alunos/$id': typeof AppAlunosIdRoute
  '/master': typeof AppMasterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alunos': typeof AppAlunosRouteWithChildren
  '/_app/mensalidades': typeof AppMensalidadesRoute
  '/_app/professores': typeof AppProfessoresRoute
  '/_app/turmas': typeof AppTurmasRoute
  '/_app/': typeof AppIndexRoute
  '/_app/alunos/$id': typeof AppAlunosIdRoute
  '/_app/master/': typeof AppMasterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alunos'
    | '/mensalidades'
    | '/professores'
    | '/turmas'
    | '/alunos/$id'
    | '/master/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/alunos'
    | '/mensalidades'
    | '/professores'
    | '/turmas'
    | '/'
    | '/alunos/$id'
    | '/master'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/alunos'
    | '/_app/mensalidades'
    | '/_app/professores'
    | '/_app/turmas'
    | '/_app/'
    | '/_app/alunos/$id'
    | '/_app/master/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/turmas': {
      id: '/_app/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof AppTurmasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/professores': {
      id: '/_app/professores'
      path: '/professores'
      fullPath: '/professores'
      preLoaderRoute: typeof AppProfessoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mensalidades': {
      id: '/_app/mensalidades'
      path: '/mensalidades'
      fullPath: '/mensalidades'
      preLoaderRoute: typeof AppMensalidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alunos': {
      id: '/_app/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AppAlunosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master/': {
      id: '/_app/master/'
      path: '/master'
      fullPath: '/master/'
      preLoaderRoute: typeof AppMasterIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alunos/$id': {
      id: '/_app/alunos/$id'
      path: '/$id'
      fullPath: '/alunos/$id'
      preLoaderRoute: typeof AppAlunosIdRouteImport
      parentRoute: typeof AppAlunosRoute
    }
  }
}

interface AppAlunosRouteChildren {
  AppAlunosIdRoute: typeof AppAlunosIdRoute
}

const AppAlunosRouteChildren: AppAlunosRouteChildren = {
  AppAlunosIdRoute: AppAlunosIdRoute,
}

const AppAlunosRouteWithChildren = AppAlunosRoute._addFileChildren(
  AppAlunosRouteChildren,
)

interface AppRouteChildren {
  AppAlunosRoute: typeof AppAlunosRouteWithChildren
  AppMensalidadesRoute: typeof AppMensalidadesRoute
  AppProfessoresRoute: typeof AppProfessoresRoute
  AppTurmasRoute: typeof AppTurmasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMasterIndexRoute: typeof AppMasterIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlunosRoute: AppAlunosRouteWithChildren,
  AppMensalidadesRoute: AppMensalidadesRoute,
  AppProfessoresRoute: AppProfessoresRoute,
  AppTurmasRoute: AppTurmasRoute,
  AppIndexRoute: AppIndexRoute,
  AppMasterIndexRoute: AppMasterIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
